# Generated by Django 5.1.4 on 2024-12-26 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=255, verbose_name="Действие")),
                ("place", models.CharField(max_length=255, verbose_name="Место")),
                ("time", models.TimeField(verbose_name="Время выполнения")),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Приятная привычка")),
                ("reward", models.CharField(blank=True, max_length=255, verbose_name="Вознаграждение")),
                ("period", models.PositiveSmallIntegerField(default=1, verbose_name="Периодичность (в днях)")),
                ("duration", models.PositiveIntegerField(verbose_name="Время на выполнение (в секундах)")),
                ("is_public", models.BooleanField(default=False, verbose_name="Публичная привычка")),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
